name: CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Çfarë ndodh këtu? Shkarkohet kodi nga repo në makinen që ekzekuton pipeline
      - name: Setup Node.js me cache
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
        # Çfarë ndodh këtu? Instalojmë Node.js dhe përdorim cache, për të përshpejtuar ndërtimet e ardhshme
      - run: npm install
        # Çfarë ndodh këtu? Instalohen të gjitha paketat npm nga package.json
      - run: npm run build --if-present
        # Çfarë ndodh këtu? Ndërtohet aplikacioni nëse ekziston script-i për build
      - run: npm test
        # Çfarë ndodh këtu? Ekzekutohen testet automatike për frontend
