name: CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js me cache
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        working-directory: react-rust-postgres/frontend

      - name: Build app
        run: npm run build --if-present
        working-directory: react-rust-postgres/frontend

      - name: Run tests
        run: npm test
        working-directory: react-rust-postgres/frontend

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: react-rust-postgres/frontend/build/